/*
 * Placeholder TFLite model for dog detection.
 *
 * This is a minimal valid TFLite flatbuffer that won't produce meaningful
 * inference results. Replace this with a trained model:
 *
 * 1. Train a MobileNet-based binary classifier (dog vs not-dog)
 *    using TensorFlow/Keras with your own training images
 * 2. Convert to TFLite with int8 quantization:
 *    converter = tf.lite.TFLiteConverter.from_keras_model(model)
 *    converter.optimizations = [tf.lite.Optimize.DEFAULT]
 *    converter.target_spec.supported_types = [tf.int8]
 *    tflite_model = converter.convert()
 * 3. Convert to C header using xxd:
 *    xxd -i dog_detect.tflite > dog_detect_model.h
 * 4. Replace the array below with the generated byte array
 *
 * Recommended model specs for ESP32-CAM:
 * - Input: 96x96x3 uint8
 * - Output: 1x2 uint8 (not_dog, dog)
 * - Size: < 300KB (fits in flash with room for firmware)
 * - Framework: MobileNetV2 with alpha=0.35
 */

#ifndef DOG_DETECT_MODEL_H
#define DOG_DETECT_MODEL_H

// Minimal placeholder model (not functional - replace with trained model)
// This is the smallest valid TFLite flatbuffer structure
alignas(8) const unsigned char dog_detect_model[] = {
    0x20, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4C, 0x33,  // TFL3 header
    0x14, 0x00, 0x20, 0x00, 0x1C, 0x00, 0x18, 0x00,
    0x14, 0x00, 0x10, 0x00, 0x0C, 0x00, 0x00, 0x00,
    0x08, 0x00, 0x04, 0x00, 0x14, 0x00, 0x00, 0x00,
    0x1C, 0x00, 0x00, 0x00, 0x88, 0x00, 0x00, 0x00,
    0xC0, 0x00, 0x00, 0x00, 0xD8, 0x01, 0x00, 0x00,
    0xE8, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00
};

const unsigned int dog_detect_model_len = sizeof(dog_detect_model);

#endif // DOG_DETECT_MODEL_H
