using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DogDoor.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddMultiUserSupport : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // This migration is fully idempotent using IF NOT EXISTS / DO-EXCEPTION blocks.
            // It is safe to run whether InitialCreate actually executed (fresh install) or
            // was recorded as applied without running (upgrade from pre-auth EnsureCreated DB).

            migrationBuilder.Sql("""
                -- Users
                CREATE TABLE IF NOT EXISTS "Users" (
                    "Id"           integer GENERATED BY DEFAULT AS IDENTITY,
                    "Email"        character varying(256) NOT NULL,
                    "PasswordHash" text                   NOT NULL,
                    "FirstName"    character varying(100),
                    "LastName"     character varying(100),
                    "Phone"        character varying(30),
                    "MobilePhone"  character varying(30),
                    "AddressLine1" character varying(200),
                    "AddressLine2" character varying(200),
                    "City"         character varying(100),
                    "State"        character varying(100),
                    "PostalCode"   character varying(20),
                    "Country"      character varying(100),
                    "EmailVerified" boolean               NOT NULL,
                    "CreatedAt"    timestamp with time zone NOT NULL,
                    "UpdatedAt"    timestamp with time zone,
                    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
                );

                -- UserGuests
                CREATE TABLE IF NOT EXISTS "UserGuests" (
                    "OwnerId"    integer                  NOT NULL,
                    "GuestId"    integer                  NOT NULL,
                    "InvitedAt"  timestamp with time zone NOT NULL,
                    "AcceptedAt" timestamp with time zone,
                    CONSTRAINT "PK_UserGuests" PRIMARY KEY ("OwnerId", "GuestId"),
                    CONSTRAINT "FK_UserGuests_Users_OwnerId" FOREIGN KEY ("OwnerId")
                        REFERENCES "Users"("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_UserGuests_Users_GuestId" FOREIGN KEY ("GuestId")
                        REFERENCES "Users"("Id") ON DELETE RESTRICT
                );

                -- Invitations
                CREATE TABLE IF NOT EXISTS "Invitations" (
                    "Id"           integer GENERATED BY DEFAULT AS IDENTITY,
                    "InvitedById"  integer                  NOT NULL,
                    "InviteeEmail" character varying(256)   NOT NULL,
                    "Token"        character varying(512)   NOT NULL,
                    "ExpiresAt"    timestamp with time zone NOT NULL,
                    "AcceptedAt"   timestamp with time zone,
                    "CreatedAt"    timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Invitations" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Invitations_Users_InvitedById" FOREIGN KEY ("InvitedById")
                        REFERENCES "Users"("Id") ON DELETE CASCADE
                );

                -- PasswordResetTokens
                CREATE TABLE IF NOT EXISTS "PasswordResetTokens" (
                    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId"    integer                  NOT NULL,
                    "Token"     character varying(512)   NOT NULL,
                    "ExpiresAt" timestamp with time zone NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "IsUsed"    boolean                  NOT NULL,
                    CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId")
                        REFERENCES "Users"("Id") ON DELETE CASCADE
                );

                -- RefreshTokens
                CREATE TABLE IF NOT EXISTS "RefreshTokens" (
                    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId"    integer                  NOT NULL,
                    "Token"     character varying(512)   NOT NULL,
                    "ExpiresAt" timestamp with time zone NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "IsRevoked" boolean                  NOT NULL,
                    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId")
                        REFERENCES "Users"("Id") ON DELETE CASCADE
                );

                -- UserId on Animals (no-op if column already exists from InitialCreate)
                ALTER TABLE "Animals" ADD COLUMN IF NOT EXISTS "UserId" integer NOT NULL DEFAULT 0;
                DO $$ BEGIN
                    ALTER TABLE "Animals" ADD CONSTRAINT "FK_Animals_Users_UserId"
                        FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE NOT VALID;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;

                -- UserId on DoorConfigurations
                ALTER TABLE "DoorConfigurations" ADD COLUMN IF NOT EXISTS "UserId" integer NOT NULL DEFAULT 0;
                DO $$ BEGIN
                    ALTER TABLE "DoorConfigurations" ADD CONSTRAINT "FK_DoorConfigurations_Users_UserId"
                        FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE NOT VALID;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;

                -- UserId on DoorEvents
                ALTER TABLE "DoorEvents" ADD COLUMN IF NOT EXISTS "UserId" integer NOT NULL DEFAULT 0;
                DO $$ BEGIN
                    ALTER TABLE "DoorEvents" ADD CONSTRAINT "FK_DoorEvents_Users_UserId"
                        FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE RESTRICT NOT VALID;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;

                -- Indices (all IF NOT EXISTS)
                CREATE INDEX IF NOT EXISTS "IX_Animals_UserId"              ON "Animals"("UserId");
                CREATE INDEX IF NOT EXISTS "IX_DoorConfigurations_UserId"   ON "DoorConfigurations"("UserId");
                CREATE INDEX IF NOT EXISTS "IX_DoorEvents_UserId"           ON "DoorEvents"("UserId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email"          ON "Users"("Email");
                CREATE INDEX IF NOT EXISTS "IX_UserGuests_GuestId"          ON "UserGuests"("GuestId");
                CREATE INDEX IF NOT EXISTS "IX_Invitations_InvitedById"     ON "Invitations"("InvitedById");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Invitations_Token"    ON "Invitations"("Token");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_PasswordResetTokens_Token" ON "PasswordResetTokens"("Token");
                CREATE INDEX IF NOT EXISTS "IX_PasswordResetTokens_UserId"  ON "PasswordResetTokens"("UserId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshTokens_Token"  ON "RefreshTokens"("Token");
                CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId"        ON "RefreshTokens"("UserId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP INDEX IF EXISTS "IX_RefreshTokens_UserId";
                DROP INDEX IF EXISTS "IX_RefreshTokens_Token";
                DROP INDEX IF EXISTS "IX_PasswordResetTokens_UserId";
                DROP INDEX IF EXISTS "IX_PasswordResetTokens_Token";
                DROP INDEX IF EXISTS "IX_Invitations_Token";
                DROP INDEX IF EXISTS "IX_Invitations_InvitedById";
                DROP INDEX IF EXISTS "IX_UserGuests_GuestId";
                DROP INDEX IF EXISTS "IX_Users_Email";
                DROP INDEX IF EXISTS "IX_DoorEvents_UserId";
                DROP INDEX IF EXISTS "IX_DoorConfigurations_UserId";
                DROP INDEX IF EXISTS "IX_Animals_UserId";

                ALTER TABLE "DoorEvents"        DROP CONSTRAINT IF EXISTS "FK_DoorEvents_Users_UserId";
                ALTER TABLE "DoorEvents"        DROP COLUMN    IF EXISTS "UserId";
                ALTER TABLE "DoorConfigurations" DROP CONSTRAINT IF EXISTS "FK_DoorConfigurations_Users_UserId";
                ALTER TABLE "DoorConfigurations" DROP COLUMN    IF EXISTS "UserId";
                ALTER TABLE "Animals"           DROP CONSTRAINT IF EXISTS "FK_Animals_Users_UserId";
                ALTER TABLE "Animals"           DROP COLUMN    IF EXISTS "UserId";

                DROP TABLE IF EXISTS "UserGuests";
                DROP TABLE IF EXISTS "Invitations";
                DROP TABLE IF EXISTS "PasswordResetTokens";
                DROP TABLE IF EXISTS "RefreshTokens";
                DROP TABLE IF EXISTS "Users";
                """);
        }
    }
}
