using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DogDoor.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddNotificationPreferences : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "NotificationPreferences" (
                    "Id"                   integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId"               integer                  NOT NULL,
                    "EmailEnabled"         boolean                  NOT NULL DEFAULT false,
                    "SmsEnabled"           boolean                  NOT NULL DEFAULT false,
                    "AnimalApproachInside" boolean                  NOT NULL DEFAULT false,
                    "AnimalApproachOutside" boolean                 NOT NULL DEFAULT false,
                    "UnknownAnimalInside"  boolean                  NOT NULL DEFAULT false,
                    "UnknownAnimalOutside" boolean                  NOT NULL DEFAULT false,
                    "DoorOpened"           boolean                  NOT NULL DEFAULT false,
                    "DoorClosed"           boolean                  NOT NULL DEFAULT false,
                    "DoorFailedOpen"       boolean                  NOT NULL DEFAULT false,
                    "DoorFailedClose"      boolean                  NOT NULL DEFAULT false,
                    "PowerDisconnected"    boolean                  NOT NULL DEFAULT false,
                    "PowerRestored"        boolean                  NOT NULL DEFAULT false,
                    "BatteryLow"           boolean                  NOT NULL DEFAULT false,
                    "BatteryCharged"       boolean                  NOT NULL DEFAULT false,
                    "UpdatedAt"            timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_NotificationPreferences_Users_UserId" FOREIGN KEY ("UserId")
                        REFERENCES "Users"("Id") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_NotificationPreferences_UserId"
                    ON "NotificationPreferences"("UserId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP INDEX IF EXISTS "IX_NotificationPreferences_UserId";
                DROP TABLE IF EXISTS "NotificationPreferences";
                """);
        }
    }
}
